import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
const dist = path.resolve(import.meta.dirname, '../apps/demo/dist');
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};
const server=createServer(async(req,res)=>{const rel=decodeURIComponent((req.url??'/').split('?')[0]);const f=path.join(dist,rel==='/'?'index.html':rel);let body; try{ body=await readFile(f); }catch{ res.writeHead(404).end('x'); return; } res.writeHead(200,{'content-type':MIME[path.extname(f)]??'application/octet-stream'}); res.end(body);});
await new Promise(r=>server.listen(4319,'127.0.0.1',r));
const b=await chromium.launch({headless:false,args:['--disable-gpu']});
const p=await b.newPage({viewport:{width:1360,height:900}});
p.on('pageerror',e=>console.log('PAGEERROR:',String(e).slice(0,300)));
p.on('console',m=>{ if(m.type()==='error') console.log('CONSOLE:',m.text().slice(0,300)); });
await p.goto('http://127.0.0.1:4319/');
await p.waitForSelector('.tiffin');
await p.fill('textarea','add an item from the first biryani restaurant and check the cart total is under 500');
await p.click('button:has-text("Run")');
await p.waitForTimeout(6000);
console.log('rows:', await p.evaluate(()=>document.querySelectorAll('.row').length));
console.log('insets:', await p.evaluate(()=>document.querySelectorAll('.row-inset').length));
console.log('thinking:', await p.evaluate(()=>document.querySelector('.thinking')?.textContent??'none'));
console.log('warn note:', await p.evaluate(()=>document.querySelector('.note.warn')?.textContent??'none'));
console.log('log text:', await p.evaluate(()=>document.querySelector('.log')?.textContent?.slice(0,300)??''));
console.log('verdict el:', await p.evaluate(()=>document.querySelector('.verdict')?.className??'ABSENT'));console.log('verdict tag:', await p.evaluate(()=>document.querySelector('.verdict-tag')?.textContent??'ABSENT'));console.log('textareas:', await p.evaluate(()=>document.querySelectorAll('textarea').length));console.log('404 url:', await p.evaluate(()=>'see console'));await p.screenshot({path:'.shots/dbg.png'});
await b.close(); server.close();
